#Ejercicio: Tenemos un texto donde queremos encontrar las palabras clave. Las palabras clave pueden ser hasta 5 y debemos pedirselas al usuario y guardarlas
#en una lista.

#Si el usuario quiere poner menos de 5 palabras clave, debera escribir "fin" para terminar introducir datos. Si el usuario introduce números o nada, debemos
#eliminarlos de la lista antes de la busqueda.

#En otra lista, debemos guardar el número de veces que aparece cada palabra clave en nuestro texto. Por ejemplo, si las palabras clave son ordenador y pórtatil
#y aparecen 5 y 7 veces respectivamente, nuestras listas deben ser así:

#    keywords=["ordenador", "portátil"]
#    count = [5,7]

#Pista: Podemos pasar de una cadena de texto a una lista de palabras mediante el método texto.split().

txt = """Seguramente hayas notado que tu productividad ha bajado desde que trabajas desde casa. Es muy importante que logremos teletrabajar efectivamente y 
de manera autorregulada. Esto se traduce en finalizar antes nuestras tareas y evitar jornadas laborales interminables. El primer consejo y uno de los más 
importantes ya te lo he dado en el apartado anterior. Tenemos que construir un espacio de trabajo en el que nos sintamos cómodos y dispongamos de todas 
las herramientas necesarias para teletrabajar. En la medida de lo posible, es importante teletrabajar siempre en el mismo lugar. De esta forma, nuestro 
cerebro asocia el sitio con la acción de trabajar y nos hará estar más focalizados en nuestras tareas"""

range(5)
keywords = []

for words in range(5):
    keyw = input("¿Qué palabra buscas?: ")
    if keyw == "fin":
        break
    elif (not keyw.isnumeric()):
        keywords.append(keyw)
    else:
        continue

print(keywords)
txt_list = txt.split()
keyw_times = []
index = 0

for keywords_times in keywords:
    times = txt_list.count(keywords[index])
    keyw_times.append(times)
    index += 1

print(keyw_times)
